--- 
- hosts: localhost
  become: yes
  tasks:
    - name: Install  Vim 
      yum:
        name: vim 
        state: latest
    - name: INstall  httpd
      yum:
        name: httpd
        state: latest
