---
- hosts: localhost
  become: yes
  tasks:
    - name: Create a working Directory
      file: 
        name: "{{working_dir}}"
        state: directory
    - name: write service list 
      lineinfile:
          path: "{{working_dir}}/services.txt"
          create: yes
          line: "{{service_list}}"
    - name: View the service list
      command: ls -la "{{share_paths['nfs']}}"
      register: cmd_output
    - name: write command module output to file
      copy:
        content: "{{cmd_output}}"
        dest: "{{working_dir}}/cmd_output.txt"
